<?xml version="1.0" encoding="UTF-8" ?>
<Package name="proactive-mobility" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="gohome" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="sethome" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="goengage" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="icon" src="icon.png" />
        <File name="base" src="html/css/base.css" />
        <File name="alert20x20" src="html/css/img/alert20x20.png" />
        <File name="app" src="html/img/menu/app.png" />
        <File name="button_off" src="html/img/page/button_off.png" />
        <File name="button_on" src="html/img/page/button_on.png" />
        <File name="warning" src="html/img/page/warning.png" />
        <File name="base" src="html/js/core/controllers/base.js" />
        <File name="module" src="html/js/core/module.js" />
        <File name="states" src="html/js/states.js" />
        <File name="English" src="html/lang/English.json" />
        <File name="French" src="html/lang/French.json" />
        <File name="German" src="html/lang/German.json" />
        <File name="Italian" src="html/lang/Italian.json" />
        <File name="Japanese" src="html/lang/Japanese.json" />
        <File name="Spanish" src="html/lang/Spanish.json" />
        <File name="din_blackalternate-webfont" src="html/no-nature/warning-mode/font/din_blackalternate-webfont.eot" />
        <File name="din_blackalternate-webfont" src="html/no-nature/warning-mode/font/din_blackalternate-webfont.svg" />
        <File name="din_blackalternate-webfont" src="html/no-nature/warning-mode/font/din_blackalternate-webfont.ttf" />
        <File name="din_blackalternate-webfont" src="html/no-nature/warning-mode/font/din_blackalternate-webfont.woff" />
        <File name="din_blackt-webfont" src="html/no-nature/warning-mode/font/din_blackt-webfont.eot" />
        <File name="din_blackt-webfont" src="html/no-nature/warning-mode/font/din_blackt-webfont.svg" />
        <File name="din_blackt-webfont" src="html/no-nature/warning-mode/font/din_blackt-webfont.ttf" />
        <File name="din_blackt-webfont" src="html/no-nature/warning-mode/font/din_blackt-webfont.woff" />
        <File name="din_bold-webfont" src="html/no-nature/warning-mode/font/din_bold-webfont.eot" />
        <File name="din_bold-webfont" src="html/no-nature/warning-mode/font/din_bold-webfont.svg" />
        <File name="din_bold-webfont" src="html/no-nature/warning-mode/font/din_bold-webfont.ttf" />
        <File name="din_bold-webfont" src="html/no-nature/warning-mode/font/din_bold-webfont.woff" />
        <File name="din_light-webfont" src="html/no-nature/warning-mode/font/din_light-webfont.eot" />
        <File name="din_light-webfont" src="html/no-nature/warning-mode/font/din_light-webfont.svg" />
        <File name="din_light-webfont" src="html/no-nature/warning-mode/font/din_light-webfont.ttf" />
        <File name="din_light-webfont" src="html/no-nature/warning-mode/font/din_light-webfont.woff" />
        <File name="din_lightalternate-webfont" src="html/no-nature/warning-mode/font/din_lightalternate-webfont.eot" />
        <File name="din_lightalternate-webfont" src="html/no-nature/warning-mode/font/din_lightalternate-webfont.svg" />
        <File name="din_lightalternate-webfont" src="html/no-nature/warning-mode/font/din_lightalternate-webfont.ttf" />
        <File name="din_lightalternate-webfont" src="html/no-nature/warning-mode/font/din_lightalternate-webfont.woff" />
        <File name="din_regular-webfont" src="html/no-nature/warning-mode/font/din_regular-webfont.eot" />
        <File name="din_regular-webfont" src="html/no-nature/warning-mode/font/din_regular-webfont.svg" />
        <File name="din_regular-webfont" src="html/no-nature/warning-mode/font/din_regular-webfont.ttf" />
        <File name="din_regular-webfont" src="html/no-nature/warning-mode/font/din_regular-webfont.woff" />
        <File name="stylesheet" src="html/no-nature/warning-mode/font/stylesheet.css" />
        <File name="bg" src="html/no-nature/warning-mode/img/bg.png" />
        <File name="warning" src="html/no-nature/warning-mode/warning.html" />
        <File name="base" src="html/partials/base.html" />
        <File name="index" src="html/index.html" />
        <File name="feedbacks" src="html/img/feedbacks/home_failure.png" />
        <File name="feedbacks" src="html/img/feedbacks/home_success.png" />
        <File name="feedbacks" src="html/img/feedbacks/home_ok.png" />
        <File name="feedbacks" src="html/img/feedbacks/look_for_home.png" />
        <File name="feedbacks" src="html/img/feedbacks/obstacle.png" />
        <File name="feedbacks" src="html/img/feedbacks/obstacle_human.png" />
        <File name="feedbacks" src="html/img/feedbacks/too_far.png" />
        <File name="feedbacks" src="html/img/feedbacks/define_home.png" />
        <File name="feedbacks" src="html/img/feedbacks/go_engage.png" />
        <File name="feedbacks" src="html/img/feedbacks/go_home.png" />
        <File name="feedbacks" src="html/img/feedbacks/wandering.png" />
        <File name="feedbacks" src="html/img/feedbacks/zone_human.png" />
        <File name="LICENSE" src="scripts/dxaruco/_naoqios/_numpy_UCS2/LICENSE.txt" />
        <File name="__config__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/__config__.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/__init__.py" />
        <File name="_distributor_init" src="scripts/dxaruco/_naoqios/_numpy_UCS2/_distributor_init.py" />
        <File name="_globals" src="scripts/dxaruco/_naoqios/_numpy_UCS2/_globals.py" />
        <File name="_import_tools" src="scripts/dxaruco/_naoqios/_numpy_UCS2/_import_tools.py" />
        <File name="libgfortran-3b85572a.so.3.0" src="scripts/dxaruco/_naoqios/_numpy_UCS2/_libs/libgfortran-3b85572a.so.3.0.0" />
        <File name="libopenblasp-r0-135a2122.2.18" src="scripts/dxaruco/_naoqios/_numpy_UCS2/_libs/libopenblasp-r0-135a2122.2.18.so" />
        <File name="add_newdocs" src="scripts/dxaruco/_naoqios/_numpy_UCS2/add_newdocs.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/compat/__init__.py" />
        <File name="_inspect" src="scripts/dxaruco/_naoqios/_numpy_UCS2/compat/_inspect.py" />
        <File name="py3k" src="scripts/dxaruco/_naoqios/_numpy_UCS2/compat/py3k.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/compat/setup.py" />
        <File name="conftest" src="scripts/dxaruco/_naoqios/_numpy_UCS2/conftest.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/__init__.py" />
        <File name="_dummy" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/_dummy.so" />
        <File name="_internal" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/_internal.py" />
        <File name="_methods" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/_methods.py" />
        <File name="arrayprint" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/arrayprint.py" />
        <File name="cversions" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/cversions.py" />
        <File name="defchararray" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/defchararray.py" />
        <File name="einsumfunc" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/einsumfunc.py" />
        <File name="fromnumeric" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/fromnumeric.py" />
        <File name="function_base" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/function_base.py" />
        <File name="generate_numpy_api" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/generate_numpy_api.py" />
        <File name="getlimits" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/getlimits.py" />
        <File name="__multiarray_api" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/__multiarray_api.h" />
        <File name="__ufunc_api" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/__ufunc_api.h" />
        <File name="_neighborhood_iterator_imp" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/_neighborhood_iterator_imp.h" />
        <File name="_numpyconfig" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/_numpyconfig.h" />
        <File name="arrayobject" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/arrayobject.h" />
        <File name="arrayscalars" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/arrayscalars.h" />
        <File name="halffloat" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/halffloat.h" />
        <File name="multiarray_api" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/multiarray_api.txt" />
        <File name="ndarrayobject" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/ndarrayobject.h" />
        <File name="ndarraytypes" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/ndarraytypes.h" />
        <File name="noprefix" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/noprefix.h" />
        <File name="npy_1_7_deprecated_api" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/npy_1_7_deprecated_api.h" />
        <File name="npy_3kcompat" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/npy_3kcompat.h" />
        <File name="npy_common" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/npy_common.h" />
        <File name="npy_cpu" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/npy_cpu.h" />
        <File name="npy_endian" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/npy_endian.h" />
        <File name="npy_interrupt" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/npy_interrupt.h" />
        <File name="npy_math" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/npy_math.h" />
        <File name="npy_no_deprecated_api" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/npy_no_deprecated_api.h" />
        <File name="npy_os" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/npy_os.h" />
        <File name="numpyconfig" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/numpyconfig.h" />
        <File name="old_defines" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/old_defines.h" />
        <File name="oldnumeric" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/oldnumeric.h" />
        <File name="ufunc_api" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/ufunc_api.txt" />
        <File name="ufuncobject" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/ufuncobject.h" />
        <File name="utils" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/include/numpy/utils.h" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/info.py" />
        <File name="libnpymath" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/lib/libnpymath.a" />
        <File name="mlib" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/lib/npy-pkg-config/mlib.ini" />
        <File name="npymath" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/lib/npy-pkg-config/npymath.ini" />
        <File name="machar" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/machar.py" />
        <File name="memmap" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/memmap.py" />
        <File name="multiarray" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/multiarray.so" />
        <File name="multiarray_tests" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/multiarray_tests.so" />
        <File name="numeric" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/numeric.py" />
        <File name="numerictypes" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/numerictypes.py" />
        <File name="operand_flag_tests" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/operand_flag_tests.so" />
        <File name="records" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/records.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/setup.py" />
        <File name="setup_common" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/setup_common.py" />
        <File name="shape_base" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/shape_base.py" />
        <File name="struct_ufunc_test" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/struct_ufunc_test.so" />
        <File name="test_rational" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/test_rational.so" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/__init__.py" />
        <File name="astype_copy" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/data/astype_copy.pkl" />
        <File name="recarray_from_file" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/data/recarray_from_file.fits" />
        <File name="test_abc" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_abc.py" />
        <File name="test_api" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_api.py" />
        <File name="test_arrayprint" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_arrayprint.py" />
        <File name="test_datetime" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_datetime.py" />
        <File name="test_defchararray" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_defchararray.py" />
        <File name="test_deprecations" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_deprecations.py" />
        <File name="test_dtype" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_dtype.py" />
        <File name="test_einsum" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_einsum.py" />
        <File name="test_errstate" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_errstate.py" />
        <File name="test_extint128" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_extint128.py" />
        <File name="test_function_base" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_function_base.py" />
        <File name="test_getlimits" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_getlimits.py" />
        <File name="test_half" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_half.py" />
        <File name="test_indexerrors" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_indexerrors.py" />
        <File name="test_indexing" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_indexing.py" />
        <File name="test_item_selection" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_item_selection.py" />
        <File name="test_longdouble" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_longdouble.py" />
        <File name="test_machar" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_machar.py" />
        <File name="test_mem_overlap" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_mem_overlap.py" />
        <File name="test_memmap" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_memmap.py" />
        <File name="test_multiarray" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_multiarray.py" />
        <File name="test_nditer" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_nditer.py" />
        <File name="test_numeric" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_numeric.py" />
        <File name="test_numerictypes" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_numerictypes.py" />
        <File name="test_print" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_print.py" />
        <File name="test_records" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_records.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_regression.py" />
        <File name="test_scalar_ctors" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_scalar_ctors.py" />
        <File name="test_scalarinherit" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_scalarinherit.py" />
        <File name="test_scalarmath" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_scalarmath.py" />
        <File name="test_scalarprint" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_scalarprint.py" />
        <File name="test_shape_base" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_shape_base.py" />
        <File name="test_ufunc" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_ufunc.py" />
        <File name="test_umath" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_umath.py" />
        <File name="test_umath_complex" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_umath_complex.py" />
        <File name="test_unicode" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/tests/test_unicode.py" />
        <File name="umath" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/umath.so" />
        <File name="umath_tests" src="scripts/dxaruco/_naoqios/_numpy_UCS2/core/umath_tests.so" />
        <File name="ctypeslib" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ctypeslib.py" />
        <File name="__config__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/__config__.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/__init__.py" />
        <File name="__version__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/__version__.py" />
        <File name="ccompiler" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/ccompiler.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/__init__.py" />
        <File name="autodist" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/autodist.py" />
        <File name="bdist_rpm" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/bdist_rpm.py" />
        <File name="build" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/build.py" />
        <File name="build_clib" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/build_clib.py" />
        <File name="build_ext" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/build_ext.py" />
        <File name="build_py" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/build_py.py" />
        <File name="build_scripts" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/build_scripts.py" />
        <File name="build_src" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/build_src.py" />
        <File name="config" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/config.py" />
        <File name="config_compiler" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/config_compiler.py" />
        <File name="develop" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/develop.py" />
        <File name="egg_info" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/egg_info.py" />
        <File name="install" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/install.py" />
        <File name="install_clib" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/install_clib.py" />
        <File name="install_data" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/install_data.py" />
        <File name="install_headers" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/install_headers.py" />
        <File name="sdist" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/command/sdist.py" />
        <File name="compat" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/compat.py" />
        <File name="conv_template" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/conv_template.py" />
        <File name="core" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/core.py" />
        <File name="cpuinfo" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/cpuinfo.py" />
        <File name="environment" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/environment.py" />
        <File name="exec_command" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/exec_command.py" />
        <File name="extension" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/extension.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/__init__.py" />
        <File name="absoft" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/absoft.py" />
        <File name="compaq" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/compaq.py" />
        <File name="g95" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/g95.py" />
        <File name="gnu" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/gnu.py" />
        <File name="hpux" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/hpux.py" />
        <File name="ibm" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/ibm.py" />
        <File name="intel" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/intel.py" />
        <File name="lahey" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/lahey.py" />
        <File name="mips" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/mips.py" />
        <File name="nag" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/nag.py" />
        <File name="none" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/none.py" />
        <File name="pathf95" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/pathf95.py" />
        <File name="pg" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/pg.py" />
        <File name="sun" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/sun.py" />
        <File name="vast" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/fcompiler/vast.py" />
        <File name="from_template" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/from_template.py" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/info.py" />
        <File name="intelccompiler" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/intelccompiler.py" />
        <File name="lib2def" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/lib2def.py" />
        <File name="line_endings" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/line_endings.py" />
        <File name="log" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/log.py" />
        <File name="gfortran_vs2003_hack" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/mingw/gfortran_vs2003_hack.c" />
        <File name="mingw32ccompiler" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/mingw32ccompiler.py" />
        <File name="misc_util" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/misc_util.py" />
        <File name="msvc9compiler" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/msvc9compiler.py" />
        <File name="msvccompiler" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/msvccompiler.py" />
        <File name="npy_pkg_config" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/npy_pkg_config.py" />
        <File name="numpy_distribution" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/numpy_distribution.py" />
        <File name="pathccompiler" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/pathccompiler.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/setup.py" />
        <File name="system_info" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/system_info.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/tests/__init__.py" />
        <File name="test_exec_command" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/tests/test_exec_command.py" />
        <File name="test_fcompiler_gnu" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/tests/test_fcompiler_gnu.py" />
        <File name="test_fcompiler_intel" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/tests/test_fcompiler_intel.py" />
        <File name="test_fcompiler_nagfor" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/tests/test_fcompiler_nagfor.py" />
        <File name="test_misc_util" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/tests/test_misc_util.py" />
        <File name="test_npy_pkg_config" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/tests/test_npy_pkg_config.py" />
        <File name="test_system_info" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/tests/test_system_info.py" />
        <File name="unixccompiler" src="scripts/dxaruco/_naoqios/_numpy_UCS2/distutils/unixccompiler.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/__init__.py" />
        <File name="basics" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/basics.py" />
        <File name="broadcasting" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/broadcasting.py" />
        <File name="byteswapping" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/byteswapping.py" />
        <File name="constants" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/constants.py" />
        <File name="creation" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/creation.py" />
        <File name="glossary" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/glossary.py" />
        <File name="indexing" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/indexing.py" />
        <File name="internals" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/internals.py" />
        <File name="misc" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/misc.py" />
        <File name="structured_arrays" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/structured_arrays.py" />
        <File name="subclassing" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/subclassing.py" />
        <File name="ufuncs" src="scripts/dxaruco/_naoqios/_numpy_UCS2/doc/ufuncs.py" />
        <File name="dual" src="scripts/dxaruco/_naoqios/_numpy_UCS2/dual.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/__init__.py" />
        <File name="__main__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/__main__.py" />
        <File name="__version__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/__version__.py" />
        <File name="auxfuncs" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/auxfuncs.py" />
        <File name="capi_maps" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/capi_maps.py" />
        <File name="cb_rules" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/cb_rules.py" />
        <File name="cfuncs" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/cfuncs.py" />
        <File name="common_rules" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/common_rules.py" />
        <File name="crackfortran" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/crackfortran.py" />
        <File name="diagnose" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/diagnose.py" />
        <File name="f2py2e" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/f2py2e.py" />
        <File name="f2py_testing" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/f2py_testing.py" />
        <File name="f90mod_rules" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/f90mod_rules.py" />
        <File name="func2subr" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/func2subr.py" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/info.py" />
        <File name="rules" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/rules.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/setup.py" />
        <File name="fortranobject" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/src/fortranobject.c" />
        <File name="fortranobject" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/src/fortranobject.h" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/__init__.py" />
        <File name="wrapmodule" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/array_from_pyobj/wrapmodule.c" />
        <File name="foo_free" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/assumed_shape/foo_free.f90" />
        <File name="foo_mod" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/assumed_shape/foo_mod.f90" />
        <File name="foo_use" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/assumed_shape/foo_use.f90" />
        <File name="precision" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/assumed_shape/precision.f90" />
        <File name="block" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/common/block.f" />
        <File name="foo" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/kind/foo.f90" />
        <File name="foo" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/mixed/foo.f" />
        <File name="foo_fixed" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/mixed/foo_fixed.f90" />
        <File name="foo_free" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/mixed/foo_free.f90" />
        <File name="constant_both" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/parameter/constant_both.f90" />
        <File name="constant_compound" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/parameter/constant_compound.f90" />
        <File name="constant_integer" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/parameter/constant_integer.f90" />
        <File name="constant_non_compound" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/parameter/constant_non_compound.f90" />
        <File name="constant_real" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/parameter/constant_real.f90" />
        <File name="inout" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/regression/inout.f90" />
        <File name="foo" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/size/foo.f90" />
        <File name="char" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/src/string/char.f90" />
        <File name="test_array_from_pyobj" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_array_from_pyobj.py" />
        <File name="test_assumed_shape" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_assumed_shape.py" />
        <File name="test_block_docstring" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_block_docstring.py" />
        <File name="test_callback" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_callback.py" />
        <File name="test_common" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_common.py" />
        <File name="test_kind" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_kind.py" />
        <File name="test_mixed" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_mixed.py" />
        <File name="test_parameter" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_parameter.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_regression.py" />
        <File name="test_return_character" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_return_character.py" />
        <File name="test_return_complex" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_return_complex.py" />
        <File name="test_return_integer" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_return_integer.py" />
        <File name="test_return_logical" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_return_logical.py" />
        <File name="test_return_real" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_return_real.py" />
        <File name="test_size" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_size.py" />
        <File name="test_string" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/test_string.py" />
        <File name="util" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/tests/util.py" />
        <File name="use_rules" src="scripts/dxaruco/_naoqios/_numpy_UCS2/f2py/use_rules.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/fft/__init__.py" />
        <File name="fftpack" src="scripts/dxaruco/_naoqios/_numpy_UCS2/fft/fftpack.py" />
        <File name="fftpack_lite" src="scripts/dxaruco/_naoqios/_numpy_UCS2/fft/fftpack_lite.so" />
        <File name="helper" src="scripts/dxaruco/_naoqios/_numpy_UCS2/fft/helper.py" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS2/fft/info.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/fft/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/fft/tests/__init__.py" />
        <File name="test_fftpack" src="scripts/dxaruco/_naoqios/_numpy_UCS2/fft/tests/test_fftpack.py" />
        <File name="test_helper" src="scripts/dxaruco/_naoqios/_numpy_UCS2/fft/tests/test_helper.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/__init__.py" />
        <File name="_datasource" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/_datasource.py" />
        <File name="_iotools" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/_iotools.py" />
        <File name="_version" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/_version.py" />
        <File name="arraypad" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/arraypad.py" />
        <File name="arraysetops" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/arraysetops.py" />
        <File name="arrayterator" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/arrayterator.py" />
        <File name="financial" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/financial.py" />
        <File name="format" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/format.py" />
        <File name="function_base" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/function_base.py" />
        <File name="index_tricks" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/index_tricks.py" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/info.py" />
        <File name="mixins" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/mixins.py" />
        <File name="nanfunctions" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/nanfunctions.py" />
        <File name="npyio" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/npyio.py" />
        <File name="polynomial" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/polynomial.py" />
        <File name="recfunctions" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/recfunctions.py" />
        <File name="scimath" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/scimath.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/setup.py" />
        <File name="shape_base" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/shape_base.py" />
        <File name="stride_tricks" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/stride_tricks.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/__init__.py" />
        <File name="py2-objarr" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/data/py2-objarr.npy" />
        <File name="py2-objarr" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/data/py2-objarr.npz" />
        <File name="py3-objarr" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/data/py3-objarr.npy" />
        <File name="py3-objarr" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/data/py3-objarr.npz" />
        <File name="python3" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/data/python3.npy" />
        <File name="win64python2" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/data/win64python2.npy" />
        <File name="test__datasource" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test__datasource.py" />
        <File name="test__iotools" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test__iotools.py" />
        <File name="test__version" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test__version.py" />
        <File name="test_arraypad" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_arraypad.py" />
        <File name="test_arraysetops" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_arraysetops.py" />
        <File name="test_arrayterator" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_arrayterator.py" />
        <File name="test_financial" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_financial.py" />
        <File name="test_format" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_format.py" />
        <File name="test_function_base" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_function_base.py" />
        <File name="test_index_tricks" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_index_tricks.py" />
        <File name="test_io" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_io.py" />
        <File name="test_mixins" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_mixins.py" />
        <File name="test_nanfunctions" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_nanfunctions.py" />
        <File name="test_packbits" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_packbits.py" />
        <File name="test_polynomial" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_polynomial.py" />
        <File name="test_recfunctions" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_recfunctions.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_regression.py" />
        <File name="test_shape_base" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_shape_base.py" />
        <File name="test_stride_tricks" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_stride_tricks.py" />
        <File name="test_twodim_base" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_twodim_base.py" />
        <File name="test_type_check" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_type_check.py" />
        <File name="test_ufunclike" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_ufunclike.py" />
        <File name="test_utils" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/tests/test_utils.py" />
        <File name="twodim_base" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/twodim_base.py" />
        <File name="type_check" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/type_check.py" />
        <File name="ufunclike" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/ufunclike.py" />
        <File name="user_array" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/user_array.py" />
        <File name="utils" src="scripts/dxaruco/_naoqios/_numpy_UCS2/lib/utils.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/linalg/__init__.py" />
        <File name="_umath_linalg" src="scripts/dxaruco/_naoqios/_numpy_UCS2/linalg/_umath_linalg.so" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS2/linalg/info.py" />
        <File name="lapack_lite" src="scripts/dxaruco/_naoqios/_numpy_UCS2/linalg/lapack_lite.so" />
        <File name="linalg" src="scripts/dxaruco/_naoqios/_numpy_UCS2/linalg/linalg.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/linalg/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/linalg/tests/__init__.py" />
        <File name="test_build" src="scripts/dxaruco/_naoqios/_numpy_UCS2/linalg/tests/test_build.py" />
        <File name="test_deprecations" src="scripts/dxaruco/_naoqios/_numpy_UCS2/linalg/tests/test_deprecations.py" />
        <File name="test_linalg" src="scripts/dxaruco/_naoqios/_numpy_UCS2/linalg/tests/test_linalg.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS2/linalg/tests/test_regression.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/__init__.py" />
        <File name="bench" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/bench.py" />
        <File name="core" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/core.py" />
        <File name="extras" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/extras.py" />
        <File name="mrecords" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/mrecords.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/tests/__init__.py" />
        <File name="test_core" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/tests/test_core.py" />
        <File name="test_deprecations" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/tests/test_deprecations.py" />
        <File name="test_extras" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/tests/test_extras.py" />
        <File name="test_mrecords" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/tests/test_mrecords.py" />
        <File name="test_old_ma" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/tests/test_old_ma.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/tests/test_regression.py" />
        <File name="test_subclassing" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/tests/test_subclassing.py" />
        <File name="testutils" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/testutils.py" />
        <File name="timer_comparison" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/timer_comparison.py" />
        <File name="version" src="scripts/dxaruco/_naoqios/_numpy_UCS2/ma/version.py" />
        <File name="matlib" src="scripts/dxaruco/_naoqios/_numpy_UCS2/matlib.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/matrixlib/__init__.py" />
        <File name="defmatrix" src="scripts/dxaruco/_naoqios/_numpy_UCS2/matrixlib/defmatrix.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/matrixlib/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/matrixlib/tests/__init__.py" />
        <File name="test_defmatrix" src="scripts/dxaruco/_naoqios/_numpy_UCS2/matrixlib/tests/test_defmatrix.py" />
        <File name="test_multiarray" src="scripts/dxaruco/_naoqios/_numpy_UCS2/matrixlib/tests/test_multiarray.py" />
        <File name="test_numeric" src="scripts/dxaruco/_naoqios/_numpy_UCS2/matrixlib/tests/test_numeric.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS2/matrixlib/tests/test_regression.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/__init__.py" />
        <File name="_polybase" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/_polybase.py" />
        <File name="chebyshev" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/chebyshev.py" />
        <File name="hermite" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/hermite.py" />
        <File name="hermite_e" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/hermite_e.py" />
        <File name="laguerre" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/laguerre.py" />
        <File name="legendre" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/legendre.py" />
        <File name="polynomial" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/polynomial.py" />
        <File name="polyutils" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/polyutils.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/tests/__init__.py" />
        <File name="test_chebyshev" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/tests/test_chebyshev.py" />
        <File name="test_classes" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/tests/test_classes.py" />
        <File name="test_hermite" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/tests/test_hermite.py" />
        <File name="test_hermite_e" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/tests/test_hermite_e.py" />
        <File name="test_laguerre" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/tests/test_laguerre.py" />
        <File name="test_legendre" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/tests/test_legendre.py" />
        <File name="test_polynomial" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/tests/test_polynomial.py" />
        <File name="test_polyutils" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/tests/test_polyutils.py" />
        <File name="test_printing" src="scripts/dxaruco/_naoqios/_numpy_UCS2/polynomial/tests/test_printing.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/random/__init__.py" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS2/random/info.py" />
        <File name="mtrand" src="scripts/dxaruco/_naoqios/_numpy_UCS2/random/mtrand.so" />
        <File name="randomkit" src="scripts/dxaruco/_naoqios/_numpy_UCS2/random/randomkit.h" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/random/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/random/tests/__init__.py" />
        <File name="test_random" src="scripts/dxaruco/_naoqios/_numpy_UCS2/random/tests/test_random.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS2/random/tests/test_regression.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/__init__.py" />
        <File name="decorators" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/decorators.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/nose_tools/__init__.py" />
        <File name="decorators" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/nose_tools/decorators.py" />
        <File name="noseclasses" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/nose_tools/noseclasses.py" />
        <File name="nosetester" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/nose_tools/nosetester.py" />
        <File name="parameterized" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/nose_tools/parameterized.py" />
        <File name="utils" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/nose_tools/utils.py" />
        <File name="noseclasses" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/noseclasses.py" />
        <File name="nosetester" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/nosetester.py" />
        <File name="print_coercion_tables" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/print_coercion_tables.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/tests/__init__.py" />
        <File name="test_decorators" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/tests/test_decorators.py" />
        <File name="test_doctesting" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/tests/test_doctesting.py" />
        <File name="test_utils" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/tests/test_utils.py" />
        <File name="utils" src="scripts/dxaruco/_naoqios/_numpy_UCS2/testing/utils.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS2/tests/__init__.py" />
        <File name="test_ctypeslib" src="scripts/dxaruco/_naoqios/_numpy_UCS2/tests/test_ctypeslib.py" />
        <File name="test_matlib" src="scripts/dxaruco/_naoqios/_numpy_UCS2/tests/test_matlib.py" />
        <File name="test_numpy_version" src="scripts/dxaruco/_naoqios/_numpy_UCS2/tests/test_numpy_version.py" />
        <File name="test_reloading" src="scripts/dxaruco/_naoqios/_numpy_UCS2/tests/test_reloading.py" />
        <File name="test_scripts" src="scripts/dxaruco/_naoqios/_numpy_UCS2/tests/test_scripts.py" />
        <File name="test_warnings" src="scripts/dxaruco/_naoqios/_numpy_UCS2/tests/test_warnings.py" />
        <File name="version" src="scripts/dxaruco/_naoqios/_numpy_UCS2/version.py" />
        <File name="LICENSE" src="scripts/dxaruco/_naoqios/_numpy_UCS4/LICENSE.txt" />
        <File name="__config__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/__config__.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/__init__.py" />
        <File name="_distributor_init" src="scripts/dxaruco/_naoqios/_numpy_UCS4/_distributor_init.py" />
        <File name="_globals" src="scripts/dxaruco/_naoqios/_numpy_UCS4/_globals.py" />
        <File name="_import_tools" src="scripts/dxaruco/_naoqios/_numpy_UCS4/_import_tools.py" />
        <File name="libgfortran-3b85572a.so.3.0" src="scripts/dxaruco/_naoqios/_numpy_UCS4/_libs/libgfortran-3b85572a.so.3.0.0" />
        <File name="libopenblasp-r0-135a2122.2.18" src="scripts/dxaruco/_naoqios/_numpy_UCS4/_libs/libopenblasp-r0-135a2122.2.18.so" />
        <File name="add_newdocs" src="scripts/dxaruco/_naoqios/_numpy_UCS4/add_newdocs.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/compat/__init__.py" />
        <File name="_inspect" src="scripts/dxaruco/_naoqios/_numpy_UCS4/compat/_inspect.py" />
        <File name="py3k" src="scripts/dxaruco/_naoqios/_numpy_UCS4/compat/py3k.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/compat/setup.py" />
        <File name="conftest" src="scripts/dxaruco/_naoqios/_numpy_UCS4/conftest.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/__init__.py" />
        <File name="_dummy" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/_dummy.so" />
        <File name="_internal" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/_internal.py" />
        <File name="_methods" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/_methods.py" />
        <File name="arrayprint" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/arrayprint.py" />
        <File name="cversions" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/cversions.py" />
        <File name="defchararray" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/defchararray.py" />
        <File name="einsumfunc" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/einsumfunc.py" />
        <File name="fromnumeric" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/fromnumeric.py" />
        <File name="function_base" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/function_base.py" />
        <File name="generate_numpy_api" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/generate_numpy_api.py" />
        <File name="getlimits" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/getlimits.py" />
        <File name="__multiarray_api" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/__multiarray_api.h" />
        <File name="__ufunc_api" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/__ufunc_api.h" />
        <File name="_neighborhood_iterator_imp" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/_neighborhood_iterator_imp.h" />
        <File name="_numpyconfig" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/_numpyconfig.h" />
        <File name="arrayobject" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/arrayobject.h" />
        <File name="arrayscalars" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/arrayscalars.h" />
        <File name="halffloat" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/halffloat.h" />
        <File name="multiarray_api" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/multiarray_api.txt" />
        <File name="ndarrayobject" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/ndarrayobject.h" />
        <File name="ndarraytypes" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/ndarraytypes.h" />
        <File name="noprefix" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/noprefix.h" />
        <File name="npy_1_7_deprecated_api" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/npy_1_7_deprecated_api.h" />
        <File name="npy_3kcompat" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/npy_3kcompat.h" />
        <File name="npy_common" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/npy_common.h" />
        <File name="npy_cpu" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/npy_cpu.h" />
        <File name="npy_endian" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/npy_endian.h" />
        <File name="npy_interrupt" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/npy_interrupt.h" />
        <File name="npy_math" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/npy_math.h" />
        <File name="npy_no_deprecated_api" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/npy_no_deprecated_api.h" />
        <File name="npy_os" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/npy_os.h" />
        <File name="numpyconfig" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/numpyconfig.h" />
        <File name="old_defines" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/old_defines.h" />
        <File name="oldnumeric" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/oldnumeric.h" />
        <File name="ufunc_api" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/ufunc_api.txt" />
        <File name="ufuncobject" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/ufuncobject.h" />
        <File name="utils" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/include/numpy/utils.h" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/info.py" />
        <File name="libnpymath" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/lib/libnpymath.a" />
        <File name="mlib" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/lib/npy-pkg-config/mlib.ini" />
        <File name="npymath" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/lib/npy-pkg-config/npymath.ini" />
        <File name="machar" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/machar.py" />
        <File name="memmap" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/memmap.py" />
        <File name="multiarray" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/multiarray.so" />
        <File name="multiarray_tests" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/multiarray_tests.so" />
        <File name="numeric" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/numeric.py" />
        <File name="numerictypes" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/numerictypes.py" />
        <File name="operand_flag_tests" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/operand_flag_tests.so" />
        <File name="records" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/records.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/setup.py" />
        <File name="setup_common" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/setup_common.py" />
        <File name="shape_base" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/shape_base.py" />
        <File name="struct_ufunc_test" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/struct_ufunc_test.so" />
        <File name="test_rational" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/test_rational.so" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/__init__.py" />
        <File name="astype_copy" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/data/astype_copy.pkl" />
        <File name="recarray_from_file" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/data/recarray_from_file.fits" />
        <File name="test_abc" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_abc.py" />
        <File name="test_api" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_api.py" />
        <File name="test_arrayprint" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_arrayprint.py" />
        <File name="test_datetime" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_datetime.py" />
        <File name="test_defchararray" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_defchararray.py" />
        <File name="test_deprecations" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_deprecations.py" />
        <File name="test_dtype" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_dtype.py" />
        <File name="test_einsum" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_einsum.py" />
        <File name="test_errstate" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_errstate.py" />
        <File name="test_extint128" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_extint128.py" />
        <File name="test_function_base" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_function_base.py" />
        <File name="test_getlimits" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_getlimits.py" />
        <File name="test_half" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_half.py" />
        <File name="test_indexerrors" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_indexerrors.py" />
        <File name="test_indexing" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_indexing.py" />
        <File name="test_item_selection" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_item_selection.py" />
        <File name="test_longdouble" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_longdouble.py" />
        <File name="test_machar" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_machar.py" />
        <File name="test_mem_overlap" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_mem_overlap.py" />
        <File name="test_memmap" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_memmap.py" />
        <File name="test_multiarray" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_multiarray.py" />
        <File name="test_nditer" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_nditer.py" />
        <File name="test_numeric" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_numeric.py" />
        <File name="test_numerictypes" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_numerictypes.py" />
        <File name="test_print" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_print.py" />
        <File name="test_records" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_records.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_regression.py" />
        <File name="test_scalar_ctors" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_scalar_ctors.py" />
        <File name="test_scalarinherit" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_scalarinherit.py" />
        <File name="test_scalarmath" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_scalarmath.py" />
        <File name="test_scalarprint" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_scalarprint.py" />
        <File name="test_shape_base" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_shape_base.py" />
        <File name="test_ufunc" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_ufunc.py" />
        <File name="test_umath" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_umath.py" />
        <File name="test_umath_complex" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_umath_complex.py" />
        <File name="test_unicode" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/tests/test_unicode.py" />
        <File name="umath" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/umath.so" />
        <File name="umath_tests" src="scripts/dxaruco/_naoqios/_numpy_UCS4/core/umath_tests.so" />
        <File name="ctypeslib" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ctypeslib.py" />
        <File name="__config__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/__config__.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/__init__.py" />
        <File name="__version__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/__version__.py" />
        <File name="ccompiler" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/ccompiler.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/__init__.py" />
        <File name="autodist" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/autodist.py" />
        <File name="bdist_rpm" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/bdist_rpm.py" />
        <File name="build" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/build.py" />
        <File name="build_clib" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/build_clib.py" />
        <File name="build_ext" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/build_ext.py" />
        <File name="build_py" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/build_py.py" />
        <File name="build_scripts" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/build_scripts.py" />
        <File name="build_src" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/build_src.py" />
        <File name="config" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/config.py" />
        <File name="config_compiler" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/config_compiler.py" />
        <File name="develop" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/develop.py" />
        <File name="egg_info" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/egg_info.py" />
        <File name="install" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/install.py" />
        <File name="install_clib" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/install_clib.py" />
        <File name="install_data" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/install_data.py" />
        <File name="install_headers" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/install_headers.py" />
        <File name="sdist" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/command/sdist.py" />
        <File name="compat" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/compat.py" />
        <File name="conv_template" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/conv_template.py" />
        <File name="core" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/core.py" />
        <File name="cpuinfo" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/cpuinfo.py" />
        <File name="environment" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/environment.py" />
        <File name="exec_command" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/exec_command.py" />
        <File name="extension" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/extension.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/__init__.py" />
        <File name="absoft" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/absoft.py" />
        <File name="compaq" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/compaq.py" />
        <File name="g95" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/g95.py" />
        <File name="gnu" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/gnu.py" />
        <File name="hpux" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/hpux.py" />
        <File name="ibm" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/ibm.py" />
        <File name="intel" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/intel.py" />
        <File name="lahey" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/lahey.py" />
        <File name="mips" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/mips.py" />
        <File name="nag" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/nag.py" />
        <File name="none" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/none.py" />
        <File name="pathf95" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/pathf95.py" />
        <File name="pg" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/pg.py" />
        <File name="sun" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/sun.py" />
        <File name="vast" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/fcompiler/vast.py" />
        <File name="from_template" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/from_template.py" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/info.py" />
        <File name="intelccompiler" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/intelccompiler.py" />
        <File name="lib2def" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/lib2def.py" />
        <File name="line_endings" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/line_endings.py" />
        <File name="log" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/log.py" />
        <File name="gfortran_vs2003_hack" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/mingw/gfortran_vs2003_hack.c" />
        <File name="mingw32ccompiler" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/mingw32ccompiler.py" />
        <File name="misc_util" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/misc_util.py" />
        <File name="msvc9compiler" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/msvc9compiler.py" />
        <File name="msvccompiler" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/msvccompiler.py" />
        <File name="npy_pkg_config" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/npy_pkg_config.py" />
        <File name="numpy_distribution" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/numpy_distribution.py" />
        <File name="pathccompiler" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/pathccompiler.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/setup.py" />
        <File name="system_info" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/system_info.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/tests/__init__.py" />
        <File name="test_exec_command" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/tests/test_exec_command.py" />
        <File name="test_fcompiler_gnu" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/tests/test_fcompiler_gnu.py" />
        <File name="test_fcompiler_intel" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/tests/test_fcompiler_intel.py" />
        <File name="test_fcompiler_nagfor" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/tests/test_fcompiler_nagfor.py" />
        <File name="test_misc_util" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/tests/test_misc_util.py" />
        <File name="test_npy_pkg_config" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/tests/test_npy_pkg_config.py" />
        <File name="test_system_info" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/tests/test_system_info.py" />
        <File name="unixccompiler" src="scripts/dxaruco/_naoqios/_numpy_UCS4/distutils/unixccompiler.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/__init__.py" />
        <File name="basics" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/basics.py" />
        <File name="broadcasting" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/broadcasting.py" />
        <File name="byteswapping" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/byteswapping.py" />
        <File name="constants" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/constants.py" />
        <File name="creation" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/creation.py" />
        <File name="glossary" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/glossary.py" />
        <File name="indexing" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/indexing.py" />
        <File name="internals" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/internals.py" />
        <File name="misc" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/misc.py" />
        <File name="structured_arrays" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/structured_arrays.py" />
        <File name="subclassing" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/subclassing.py" />
        <File name="ufuncs" src="scripts/dxaruco/_naoqios/_numpy_UCS4/doc/ufuncs.py" />
        <File name="dual" src="scripts/dxaruco/_naoqios/_numpy_UCS4/dual.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/__init__.py" />
        <File name="__main__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/__main__.py" />
        <File name="__version__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/__version__.py" />
        <File name="auxfuncs" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/auxfuncs.py" />
        <File name="capi_maps" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/capi_maps.py" />
        <File name="cb_rules" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/cb_rules.py" />
        <File name="cfuncs" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/cfuncs.py" />
        <File name="common_rules" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/common_rules.py" />
        <File name="crackfortran" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/crackfortran.py" />
        <File name="diagnose" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/diagnose.py" />
        <File name="f2py2e" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/f2py2e.py" />
        <File name="f2py_testing" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/f2py_testing.py" />
        <File name="f90mod_rules" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/f90mod_rules.py" />
        <File name="func2subr" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/func2subr.py" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/info.py" />
        <File name="rules" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/rules.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/setup.py" />
        <File name="fortranobject" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/src/fortranobject.c" />
        <File name="fortranobject" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/src/fortranobject.h" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/__init__.py" />
        <File name="wrapmodule" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/array_from_pyobj/wrapmodule.c" />
        <File name="foo_free" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/assumed_shape/foo_free.f90" />
        <File name="foo_mod" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/assumed_shape/foo_mod.f90" />
        <File name="foo_use" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/assumed_shape/foo_use.f90" />
        <File name="precision" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/assumed_shape/precision.f90" />
        <File name="block" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/common/block.f" />
        <File name="foo" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/kind/foo.f90" />
        <File name="foo" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/mixed/foo.f" />
        <File name="foo_fixed" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/mixed/foo_fixed.f90" />
        <File name="foo_free" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/mixed/foo_free.f90" />
        <File name="constant_both" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/parameter/constant_both.f90" />
        <File name="constant_compound" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/parameter/constant_compound.f90" />
        <File name="constant_integer" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/parameter/constant_integer.f90" />
        <File name="constant_non_compound" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/parameter/constant_non_compound.f90" />
        <File name="constant_real" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/parameter/constant_real.f90" />
        <File name="inout" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/regression/inout.f90" />
        <File name="foo" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/size/foo.f90" />
        <File name="char" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/src/string/char.f90" />
        <File name="test_array_from_pyobj" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_array_from_pyobj.py" />
        <File name="test_assumed_shape" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_assumed_shape.py" />
        <File name="test_block_docstring" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_block_docstring.py" />
        <File name="test_callback" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_callback.py" />
        <File name="test_common" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_common.py" />
        <File name="test_kind" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_kind.py" />
        <File name="test_mixed" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_mixed.py" />
        <File name="test_parameter" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_parameter.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_regression.py" />
        <File name="test_return_character" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_return_character.py" />
        <File name="test_return_complex" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_return_complex.py" />
        <File name="test_return_integer" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_return_integer.py" />
        <File name="test_return_logical" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_return_logical.py" />
        <File name="test_return_real" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_return_real.py" />
        <File name="test_size" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_size.py" />
        <File name="test_string" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/test_string.py" />
        <File name="util" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/tests/util.py" />
        <File name="use_rules" src="scripts/dxaruco/_naoqios/_numpy_UCS4/f2py/use_rules.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/fft/__init__.py" />
        <File name="fftpack" src="scripts/dxaruco/_naoqios/_numpy_UCS4/fft/fftpack.py" />
        <File name="fftpack_lite" src="scripts/dxaruco/_naoqios/_numpy_UCS4/fft/fftpack_lite.so" />
        <File name="helper" src="scripts/dxaruco/_naoqios/_numpy_UCS4/fft/helper.py" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS4/fft/info.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/fft/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/fft/tests/__init__.py" />
        <File name="test_fftpack" src="scripts/dxaruco/_naoqios/_numpy_UCS4/fft/tests/test_fftpack.py" />
        <File name="test_helper" src="scripts/dxaruco/_naoqios/_numpy_UCS4/fft/tests/test_helper.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/__init__.py" />
        <File name="_datasource" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/_datasource.py" />
        <File name="_iotools" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/_iotools.py" />
        <File name="_version" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/_version.py" />
        <File name="arraypad" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/arraypad.py" />
        <File name="arraysetops" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/arraysetops.py" />
        <File name="arrayterator" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/arrayterator.py" />
        <File name="financial" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/financial.py" />
        <File name="format" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/format.py" />
        <File name="function_base" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/function_base.py" />
        <File name="index_tricks" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/index_tricks.py" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/info.py" />
        <File name="mixins" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/mixins.py" />
        <File name="nanfunctions" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/nanfunctions.py" />
        <File name="npyio" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/npyio.py" />
        <File name="polynomial" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/polynomial.py" />
        <File name="recfunctions" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/recfunctions.py" />
        <File name="scimath" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/scimath.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/setup.py" />
        <File name="shape_base" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/shape_base.py" />
        <File name="stride_tricks" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/stride_tricks.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/__init__.py" />
        <File name="py2-objarr" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/data/py2-objarr.npy" />
        <File name="py2-objarr" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/data/py2-objarr.npz" />
        <File name="py3-objarr" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/data/py3-objarr.npy" />
        <File name="py3-objarr" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/data/py3-objarr.npz" />
        <File name="python3" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/data/python3.npy" />
        <File name="win64python2" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/data/win64python2.npy" />
        <File name="test__datasource" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test__datasource.py" />
        <File name="test__iotools" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test__iotools.py" />
        <File name="test__version" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test__version.py" />
        <File name="test_arraypad" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_arraypad.py" />
        <File name="test_arraysetops" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_arraysetops.py" />
        <File name="test_arrayterator" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_arrayterator.py" />
        <File name="test_financial" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_financial.py" />
        <File name="test_format" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_format.py" />
        <File name="test_function_base" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_function_base.py" />
        <File name="test_index_tricks" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_index_tricks.py" />
        <File name="test_io" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_io.py" />
        <File name="test_mixins" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_mixins.py" />
        <File name="test_nanfunctions" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_nanfunctions.py" />
        <File name="test_packbits" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_packbits.py" />
        <File name="test_polynomial" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_polynomial.py" />
        <File name="test_recfunctions" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_recfunctions.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_regression.py" />
        <File name="test_shape_base" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_shape_base.py" />
        <File name="test_stride_tricks" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_stride_tricks.py" />
        <File name="test_twodim_base" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_twodim_base.py" />
        <File name="test_type_check" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_type_check.py" />
        <File name="test_ufunclike" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_ufunclike.py" />
        <File name="test_utils" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/tests/test_utils.py" />
        <File name="twodim_base" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/twodim_base.py" />
        <File name="type_check" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/type_check.py" />
        <File name="ufunclike" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/ufunclike.py" />
        <File name="user_array" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/user_array.py" />
        <File name="utils" src="scripts/dxaruco/_naoqios/_numpy_UCS4/lib/utils.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/linalg/__init__.py" />
        <File name="_umath_linalg" src="scripts/dxaruco/_naoqios/_numpy_UCS4/linalg/_umath_linalg.so" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS4/linalg/info.py" />
        <File name="lapack_lite" src="scripts/dxaruco/_naoqios/_numpy_UCS4/linalg/lapack_lite.so" />
        <File name="linalg" src="scripts/dxaruco/_naoqios/_numpy_UCS4/linalg/linalg.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/linalg/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/linalg/tests/__init__.py" />
        <File name="test_build" src="scripts/dxaruco/_naoqios/_numpy_UCS4/linalg/tests/test_build.py" />
        <File name="test_deprecations" src="scripts/dxaruco/_naoqios/_numpy_UCS4/linalg/tests/test_deprecations.py" />
        <File name="test_linalg" src="scripts/dxaruco/_naoqios/_numpy_UCS4/linalg/tests/test_linalg.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS4/linalg/tests/test_regression.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/__init__.py" />
        <File name="bench" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/bench.py" />
        <File name="core" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/core.py" />
        <File name="extras" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/extras.py" />
        <File name="mrecords" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/mrecords.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/tests/__init__.py" />
        <File name="test_core" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/tests/test_core.py" />
        <File name="test_deprecations" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/tests/test_deprecations.py" />
        <File name="test_extras" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/tests/test_extras.py" />
        <File name="test_mrecords" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/tests/test_mrecords.py" />
        <File name="test_old_ma" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/tests/test_old_ma.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/tests/test_regression.py" />
        <File name="test_subclassing" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/tests/test_subclassing.py" />
        <File name="testutils" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/testutils.py" />
        <File name="timer_comparison" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/timer_comparison.py" />
        <File name="version" src="scripts/dxaruco/_naoqios/_numpy_UCS4/ma/version.py" />
        <File name="matlib" src="scripts/dxaruco/_naoqios/_numpy_UCS4/matlib.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/matrixlib/__init__.py" />
        <File name="defmatrix" src="scripts/dxaruco/_naoqios/_numpy_UCS4/matrixlib/defmatrix.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/matrixlib/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/matrixlib/tests/__init__.py" />
        <File name="test_defmatrix" src="scripts/dxaruco/_naoqios/_numpy_UCS4/matrixlib/tests/test_defmatrix.py" />
        <File name="test_multiarray" src="scripts/dxaruco/_naoqios/_numpy_UCS4/matrixlib/tests/test_multiarray.py" />
        <File name="test_numeric" src="scripts/dxaruco/_naoqios/_numpy_UCS4/matrixlib/tests/test_numeric.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS4/matrixlib/tests/test_regression.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/__init__.py" />
        <File name="_polybase" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/_polybase.py" />
        <File name="chebyshev" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/chebyshev.py" />
        <File name="hermite" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/hermite.py" />
        <File name="hermite_e" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/hermite_e.py" />
        <File name="laguerre" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/laguerre.py" />
        <File name="legendre" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/legendre.py" />
        <File name="polynomial" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/polynomial.py" />
        <File name="polyutils" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/polyutils.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/tests/__init__.py" />
        <File name="test_chebyshev" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/tests/test_chebyshev.py" />
        <File name="test_classes" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/tests/test_classes.py" />
        <File name="test_hermite" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/tests/test_hermite.py" />
        <File name="test_hermite_e" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/tests/test_hermite_e.py" />
        <File name="test_laguerre" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/tests/test_laguerre.py" />
        <File name="test_legendre" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/tests/test_legendre.py" />
        <File name="test_polynomial" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/tests/test_polynomial.py" />
        <File name="test_polyutils" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/tests/test_polyutils.py" />
        <File name="test_printing" src="scripts/dxaruco/_naoqios/_numpy_UCS4/polynomial/tests/test_printing.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/random/__init__.py" />
        <File name="info" src="scripts/dxaruco/_naoqios/_numpy_UCS4/random/info.py" />
        <File name="mtrand" src="scripts/dxaruco/_naoqios/_numpy_UCS4/random/mtrand.so" />
        <File name="randomkit" src="scripts/dxaruco/_naoqios/_numpy_UCS4/random/randomkit.h" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/random/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/random/tests/__init__.py" />
        <File name="test_random" src="scripts/dxaruco/_naoqios/_numpy_UCS4/random/tests/test_random.py" />
        <File name="test_regression" src="scripts/dxaruco/_naoqios/_numpy_UCS4/random/tests/test_regression.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/__init__.py" />
        <File name="decorators" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/decorators.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/nose_tools/__init__.py" />
        <File name="decorators" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/nose_tools/decorators.py" />
        <File name="noseclasses" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/nose_tools/noseclasses.py" />
        <File name="nosetester" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/nose_tools/nosetester.py" />
        <File name="parameterized" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/nose_tools/parameterized.py" />
        <File name="utils" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/nose_tools/utils.py" />
        <File name="noseclasses" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/noseclasses.py" />
        <File name="nosetester" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/nosetester.py" />
        <File name="print_coercion_tables" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/print_coercion_tables.py" />
        <File name="setup" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/setup.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/tests/__init__.py" />
        <File name="test_decorators" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/tests/test_decorators.py" />
        <File name="test_doctesting" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/tests/test_doctesting.py" />
        <File name="test_utils" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/tests/test_utils.py" />
        <File name="utils" src="scripts/dxaruco/_naoqios/_numpy_UCS4/testing/utils.py" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/_numpy_UCS4/tests/__init__.py" />
        <File name="test_ctypeslib" src="scripts/dxaruco/_naoqios/_numpy_UCS4/tests/test_ctypeslib.py" />
        <File name="test_matlib" src="scripts/dxaruco/_naoqios/_numpy_UCS4/tests/test_matlib.py" />
        <File name="test_numpy_version" src="scripts/dxaruco/_naoqios/_numpy_UCS4/tests/test_numpy_version.py" />
        <File name="test_reloading" src="scripts/dxaruco/_naoqios/_numpy_UCS4/tests/test_reloading.py" />
        <File name="test_scripts" src="scripts/dxaruco/_naoqios/_numpy_UCS4/tests/test_scripts.py" />
        <File name="test_warnings" src="scripts/dxaruco/_naoqios/_numpy_UCS4/tests/test_warnings.py" />
        <File name="version" src="scripts/dxaruco/_naoqios/_numpy_UCS4/version.py" />
        <File name="LICENSE-3RD-PARTY" src="scripts/dxaruco/_naoqios/cv2/LICENSE-3RD-PARTY.txt" />
        <File name="LICENSE" src="scripts/dxaruco/_naoqios/cv2/LICENSE.txt" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/cv2/__init__.py" />
        <File name="libQtCore-1b301c71.so.4.8" src="scripts/dxaruco/_naoqios/cv2/_libs/libQtCore-1b301c71.so.4.8.7" />
        <File name="libQtGui-55070e59.so.4.8" src="scripts/dxaruco/_naoqios/cv2/_libs/libQtGui-55070e59.so.4.8.7" />
        <File name="libQtTest-0cf8861e.so.4.8" src="scripts/dxaruco/_naoqios/cv2/_libs/libQtTest-0cf8861e.so.4.8.7" />
        <File name="libavcodec-f8b41ff2.so.58.6" src="scripts/dxaruco/_naoqios/cv2/_libs/libavcodec-f8b41ff2.so.58.6.103" />
        <File name="libavformat-557d2fb9.so.58.3" src="scripts/dxaruco/_naoqios/cv2/_libs/libavformat-557d2fb9.so.58.3.100" />
        <File name="libavutil-a914ceb9.so.56.5" src="scripts/dxaruco/_naoqios/cv2/_libs/libavutil-a914ceb9.so.56.5.100" />
        <File name="libswresample-bd16ac6c.so.3.0" src="scripts/dxaruco/_naoqios/cv2/_libs/libswresample-bd16ac6c.so.3.0.101" />
        <File name="libswscale-c60cb469.so.5.0" src="scripts/dxaruco/_naoqios/cv2/_libs/libswscale-c60cb469.so.5.0.101" />
        <File name="libz-83853723.so.1.2" src="scripts/dxaruco/_naoqios/cv2/_libs/libz-83853723.so.1.2.3" />
        <File name="cv2" src="scripts/dxaruco/_naoqios/cv2/cv2.so" />
        <File name="__init__" src="scripts/dxaruco/_naoqios/cv2/data/__init__.py" />
        <File name="haarcascade_eye" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_eye.xml" />
        <File name="haarcascade_eye_tree_eyeglasses" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_eye_tree_eyeglasses.xml" />
        <File name="haarcascade_frontalcatface" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_frontalcatface.xml" />
        <File name="haarcascade_frontalcatface_extended" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_frontalcatface_extended.xml" />
        <File name="haarcascade_frontalface_alt" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_frontalface_alt.xml" />
        <File name="haarcascade_frontalface_alt2" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_frontalface_alt2.xml" />
        <File name="haarcascade_frontalface_alt_tree" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_frontalface_alt_tree.xml" />
        <File name="haarcascade_frontalface_default" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_frontalface_default.xml" />
        <File name="haarcascade_fullbody" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_fullbody.xml" />
        <File name="haarcascade_lefteye_2splits" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_lefteye_2splits.xml" />
        <File name="haarcascade_licence_plate_rus_16stages" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_licence_plate_rus_16stages.xml" />
        <File name="haarcascade_lowerbody" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_lowerbody.xml" />
        <File name="haarcascade_profileface" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_profileface.xml" />
        <File name="haarcascade_righteye_2splits" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_righteye_2splits.xml" />
        <File name="haarcascade_russian_plate_number" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_russian_plate_number.xml" />
        <File name="haarcascade_smile" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_smile.xml" />
        <File name="haarcascade_upperbody" src="scripts/dxaruco/_naoqios/cv2/data/haarcascade_upperbody.xml" />
        <File name="dxaruco" src="scripts/dxaruco/dxaruco.py" />
        <File name="arucomanager" src="scripts/dxhomefinder/arucomanager.py" />
        <File name="positions" src="scripts/dxhomefinder/data/positions.txt" />
        <File name="dxhomefinder" src="scripts/dxhomefinder/dxhomefinder.py" />
        <File name="measure" src="scripts/dxhomefinder/measure.py" />
        <File name="move" src="scripts/dxhomefinder/move.py" />
        <File name="planeutils" src="scripts/dxhomefinder/planeutils.py" />
        <File name="podmanager" src="scripts/dxhomefinder/podmanager.py" />
        <File name="positionmanager" src="scripts/dxhomefinder/positionmanager.py" />
        <File name="slammanager" src="scripts/dxhomefinder/slammanager.py" />
        <File name="__init__" src="scripts/dxhomefinder/stk/__init__.py" />
        <File name="coroutines" src="scripts/dxhomefinder/stk/coroutines.py" />
        <File name="events" src="scripts/dxhomefinder/stk/events.py" />
        <File name="logging" src="scripts/dxhomefinder/stk/logging.py" />
        <File name="runner" src="scripts/dxhomefinder/stk/runner.py" />
        <File name="services" src="scripts/dxhomefinder/stk/services.py" />
        <File name="dxproactivemobility" src="scripts/dxproactivemobility/dxproactivemobility.py" />
        <File name="preferences" src="scripts/dxproactivemobility/preferences.py" />
        <File name="__init__" src="scripts/dxproactivemobility/stk/__init__.py" />
        <File name="events" src="scripts/dxproactivemobility/stk/events.py" />
        <File name="logging" src="scripts/dxproactivemobility/stk/logging.py" />
        <File name="runner" src="scripts/dxproactivemobility/stk/runner.py" />
        <File name="services" src="scripts/dxproactivemobility/stk/services.py" />
        <File name="translate" src="scripts/dxproactivemobility/translate.py" />
        <File name="tablet" src="scripts/dxproactivemobility/tablet.py" />
    </Resources>
    <Topics />
    <IgnoredPaths>
        <Path src=".metadata" />
    </IgnoredPaths>
</Package>
